### PR TITLE
Api

### PR DESCRIPTION
**Pull request by brandonjank**
Basic API for registering a new device, generating an api token, posting status updates, and getting config info. Resolves issue #25 

CURL REGISTER EXAMPLE:
```bash
curl -X POST https://smartsettia.com/api/register \
 -H "Accept: application/json" \
 -H "Content-Type: application/json" \
 -d '{"uuid": "4dbc0776-9b44-11e7-abc4-cec278b6b50a", "challenge": "temppass"}'
```

PYTHON REQUESTS REGISTER EXAMPLE:
```python
url = "https://smartsettia.com/api/register"
data = {"uuid": "4dbc0776-9b44-11e7-abc4-cec278b6b50a", "challenge": "temppass"}
headers = {'Content-type': 'application/json', 'Accept': 'application/json'}
response = requests.post(url, data=json.dumps(data), headers=headers)
```

SERVER RESPONSE (Note that if a new record is created, 201 is returned instead of 200 for a registration that exists):
```
HTTP/1.1 200 OK                                                               
date: Mon, 18 Sep 2017 17:10:25 GMT                                           
server: Apache/2.4.7 (Ubuntu)                                                 
cache-control: no-cache, private                                              
x-ratelimit-limit: 60                                                         
x-ratelimit-remaining: 59                                                     
content-length: 154                                                           
keep-alive: timeout=5, max=100                                                
content-type: application/json                                                
X-BACKEND: apps-proxy                                                         
                                                                              
{"data":{"name":"New Device","uuid":"9dbc0776-9b44-11e7-abc4-cec278b6b50a","id":6,"token":"u0tQGeyuGdikOOFWhfDfwxbR2Z7rTN9Hc5hZN1JHsg4uUfkTi8UUu5nh0XLm"}}
```

CURL UPDATE EXAMPLE:
```bash
curl -X POST https://smartsettia.com/api/update \
 -H "Accept: application/json" \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer u0tQGeyuGdikOOFWhfDfwxbR2Z7rTN9Hc5hZN1JHsg4uUfkTi8UUu5nh0XLm" \
 -d '{"uuid": "9dbc0776-9b44-11e7-abc4-cec278b6b50a", "token": "u0tQGeyuGdikOOFWhfDfwxbR2Z7rTN9Hc5hZN1JHsg4uUfkTi8UUu5nh0XLm", "version": "0.1.1", "hostname": "device.local", "ip": "192.168.1.213", "mac_address": "1122334455667788", "time": "2000-12-31 23:59:59", "cover_status": "closed", "error_msg": "", "limitsw_open": "0", "limitsw_closed": "1", "light_in": "0", "light_out": "100", "cpu_temp": "30", "temperature": "28", "humidity": "34"}'
```

PYTHON REQUESTS UPDATE EXAMPLE:
```python
url = "https://smartsettia.com/api/update"
data = {"uuid": "4dbc0776-9b44-11e7-abc4-cec278b6b50a", "token": "u0tQGeyuGdikOOFWhfDfwxbR2Z7rTN9Hc5hZN1JHsg4uUfkTi8UUu5nh0XLm", "version": "0.1.1", "hostname": "device.local", "ip": "192.168.1.213", "mac_address": "1122334455667788", "time": "2000-12-31 23:59:59", "cover_status": "closed", "error_msg": "", "limitsw_open": "0", "limitsw_closed": "1", "light_in": "0", "light_out": "100", "cpu_temp": "30", "temperature": "28", "humidity": "34"}
headers = {'Content-type': 'application/json', 'Accept': 'application/json', 'Authorization': 'Bearer u0tQGeyuGdikOOFWhfDfwxbR2Z7rTN9Hc5hZN1JHsg4uUfkTi8UUu5nh0XLm'}
response = requests.post(url, data=json.dumps(data), headers=headers)
```

### CODE REVIEW

**Comment by Cyberzoid1** [comment]
Looks like all is in order per our conversation. Since this is the initial push, I will have to finish the Device interface to play around with how this works.

**Comment by brandonjank** [comment]
Add example usage from the command line with curl and using python requests library to the description.

**Comment by Cyberzoid1** [comment]
Such things would be better in the github wiki

**Comment by brec9824** [comment]
You are adding allot of attributes to the devices table and allot of them should be put into other tables. I am fine with merging this for now, but this will mean we will need to empty the devices table when the new tables are added. Which isn't a big deal but it will have to be done.

**Pull request merged**
