### PR TITLE
Add time to device.index, fix delete/restore for device.index and user.index

### PR DESCRIPTION
**Pull request by brandonjank**
Added human readable time the device was last updated to device.index.
Made soft deleted devices/users show up in trash.
You can now restore devices/users from the trash.

image

### CODE REVIEW

**Comment by brandonjank** [comment]
@brec9824 should be fixed in 296b64b

**Comment by brec9824** [comment]
@brandonjank Soft deleted users aren't showing up in the trash tab for users. On the devices trash tab when I click delete I get redirected to the devices normal tab but when I go back to the trash tab the device I permanently deleted is still there.

**Comment by brandonjank** [comment]
Ment to just do this for the device controller. I went ahead and renamed the PR and updated the user as well. See 35ec6fe

**Comment by brandonjank** [comment]
@brec9824 see anything else?

**Pull request merged**
